services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:5173"
    container_name: vite-react-container
    volumes:
      - .:/app
      - /app/node_modules